//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoclickerFirestone.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TrainedGuardian {
            get {
                return ((int)(this["TrainedGuardian"]));
            }
            set {
                this["TrainedGuardian"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UpgradeMode {
            get {
                return ((int)(this["UpgradeMode"]));
            }
            set {
                this["UpgradeMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string TotalSquads {
            get {
                return ((string)(this["TotalSquads"]));
            }
            set {
                this["TotalSquads"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string offsetX {
            get {
                return ((string)(this["offsetX"]));
            }
            set {
                this["offsetX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public string cycleDurationSeconds {
            get {
                return ((string)(this["cycleDurationSeconds"]));
            }
            set {
                this["cycleDurationSeconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70")]
        public string ResearchScrollAmount1 {
            get {
                return ((string)(this["ResearchScrollAmount1"]));
            }
            set {
                this["ResearchScrollAmount1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string ResearchScrollAmount2 {
            get {
                return ((string)(this["ResearchScrollAmount2"]));
            }
            set {
                this["ResearchScrollAmount2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DoResearch1 {
            get {
                return ((bool)(this["DoResearch1"]));
            }
            set {
                this["DoResearch1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DoResearch2 {
            get {
                return ((bool)(this["DoResearch2"]));
            }
            set {
                this["DoResearch2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseDustForGuardian {
            get {
                return ((bool)(this["UseDustForGuardian"]));
            }
            set {
                this["UseDustForGuardian"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ResearchScrollLeft1 {
            get {
                return ((bool)(this["ResearchScrollLeft1"]));
            }
            set {
                this["ResearchScrollLeft1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ResearchScrollLeft2 {
            get {
                return ((bool)(this["ResearchScrollLeft2"]));
            }
            set {
                this["ResearchScrollLeft2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public string StopSubUpgradesAfterStage {
            get {
                return ((string)(this["StopSubUpgradesAfterStage"]));
            }
            set {
                this["StopSubUpgradesAfterStage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TaskUpgradeHeroes {
            get {
                return ((bool)(this["TaskUpgradeHeroes"]));
            }
            set {
                this["TaskUpgradeHeroes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TaskOracleRituals {
            get {
                return ((bool)(this["TaskOracleRituals"]));
            }
            set {
                this["TaskOracleRituals"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TaskGuildExpeditions {
            get {
                return ((bool)(this["TaskGuildExpeditions"]));
            }
            set {
                this["TaskGuildExpeditions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TaskAlchemist {
            get {
                return ((bool)(this["TaskAlchemist"]));
            }
            set {
                this["TaskAlchemist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TaskFirestoneResearch {
            get {
                return ((bool)(this["TaskFirestoneResearch"]));
            }
            set {
                this["TaskFirestoneResearch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TaskTrainGuardian {
            get {
                return ((bool)(this["TaskTrainGuardian"]));
            }
            set {
                this["TaskTrainGuardian"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TaskCampaignMissions {
            get {
                return ((bool)(this["TaskCampaignMissions"]));
            }
            set {
                this["TaskCampaignMissions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TaskAutoclick {
            get {
                return ((bool)(this["TaskAutoclick"]));
            }
            set {
                this["TaskAutoclick"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AlchemistDragonBlood {
            get {
                return ((bool)(this["AlchemistDragonBlood"]));
            }
            set {
                this["AlchemistDragonBlood"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AlchemistStrangeDust {
            get {
                return ((bool)(this["AlchemistStrangeDust"]));
            }
            set {
                this["AlchemistStrangeDust"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AlchemistExoticCoin {
            get {
                return ((bool)(this["AlchemistExoticCoin"]));
            }
            set {
                this["AlchemistExoticCoin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TaskMeteoriteResearch {
            get {
                return ((bool)(this["TaskMeteoriteResearch"]));
            }
            set {
                this["TaskMeteoriteResearch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TaskDailyMissionsLiberations {
            get {
                return ((bool)(this["TaskDailyMissionsLiberations"]));
            }
            set {
                this["TaskDailyMissionsLiberations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TaskCampaignLoot {
            get {
                return ((bool)(this["TaskCampaignLoot"]));
            }
            set {
                this["TaskCampaignLoot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TaskEngineerReward {
            get {
                return ((bool)(this["TaskEngineerReward"]));
            }
            set {
                this["TaskEngineerReward"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TaskDailyMissionsDungeons {
            get {
                return ((bool)(this["TaskDailyMissionsDungeons"]));
            }
            set {
                this["TaskDailyMissionsDungeons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TaskDailyReward {
            get {
                return ((bool)(this["TaskDailyReward"]));
            }
            set {
                this["TaskDailyReward"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TaskQuests {
            get {
                return ((bool)(this["TaskQuests"]));
            }
            set {
                this["TaskQuests"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TaskPickaxes {
            get {
                return ((bool)(this["TaskPickaxes"]));
            }
            set {
                this["TaskPickaxes"] = value;
            }
        }
    }
}
